/**
 * Default reflection questions that rotate when reflection task is enabled.
 * Each question prompts the user for a brief morning reflection.
 */

export const DEFAULT_REFLECTION_QUESTIONS = [
  "What's your goal for today?",
  "What do you want to achieve in life?",
  "Are you on the right track?",
  "What are you grateful for?",
  "What's one thing you want to improve today?",
  "What did you do yesterday that you're proud of?",
  "What's one decision you've been avoiding?",
  "What does progress look like for you today?",
  "What's draining your energy right now?",
  "What's one small win you can celebrate this evening?",
  "How are you investing in yourself this week?",
  "What habits are helping you move forward?",
  "What habits are secretly holding you back?",
  "What would your future self thank you for doing today?",
  "What's the next step you need to take toward your biggest goal?",
  "When did you feel most focused recently, and why?",
  "What's one fear you need to confront this week?",
  "Are your actions aligned with your long-term values?",
  "What can you say no to, so you can say yes to what matters?",
  "What would a fully committed version of you do today?",
  "What is the most important thing you must accomplish today?",
  "How do you want to feel at the end of today?",
  "What energy do you want to bring to today?",
  "What mindset will set you up for success today?",
  "What is one thing that excites you about today?",
  "What challenge are you ready to face today?",
  "Who do you need to become to reach your goals?",
  "What is stopping you from going all in today?",
  "What promise are you making to yourself today?",
  "What legacy do you want to build today?",
  "What is your why for getting out of bed today?",
  "What dreams are you one step closer to today?",
  "What bold move can you make today?",
  "What excuse are you leaving behind today?",
  "What proof do you need that you're capable?",
  "What would you do if you were not afraid today?",
  "What small action can create momentum today?",
  "What is the price of staying the same?",
  "What is the cost of not trying?",
  "What story do you want to tell tonight?",
  "What boundary will you protect today?",
  "What standard will you hold yourself to today?",
  "What discipline are you building today?",
  "What distraction will you refuse today?",
  "What priority will you not compromise today?",
  "What value will you lead with today?",
  "What action proves you're serious today?",
  "What will make today non-negotiable?",
  "What Victor's mindset will you adopt today?",
  "What complaint will you not make today?",
  "What complaint are you ready to drop?",
  "What is one thing you can control today?",
  "What is one thing you cannot control?",
  "How will you respond if things go wrong today?",
  "What lesson from yesterday informs today?",
  "What improvement can you make over yesterday?",
  "What momentum are you carrying into today?",
  "What reset are you giving yourself today?",
  "What fresh start are you claiming today?",
  "What peace do you need before you begin?",
  "What clarity do you need before you start?",
  "What focus will you protect today?",
  "What focus will you not sacrifice today?",
  "What confidence do you need to access today?",
  "What courage do you need to summon today?",
  "What strength are you drawing from today?",
  "What resilience are you practicing today?",
  "What patience will you need today?",
  "What persistence will carry you through today?",
  "What gratitude will anchor you today?",
  "What joy can you find today?",
  "What purpose are you living today?",
  "What passion will you channel today?",
  "What integrity will you display today?",
  "What authenticity will you show today?",
  "What kindness will you practice today?",
  "What compassion will you offer today?",
  "What self-respect will you honor today?",
  "What self-care will you prioritize today?",
  "What health habit will you commit to today?",
  "What mental habit will you upgrade today?",
  "What emotional habit will you master today?",
  "What physical energy do you need today?",
  "What mental clarity do you need today?",
  "What emotional balance do you need today?",
  "What spiritual connection do you need today?",
  "What relationship will you nurture today?",
  "What relationship will you set boundaries in today?",
  "What teamwork will you show today?",
  "What leadership will you exercise today?",
  "What communication will you improve today?",
  "What listening will you practice today?",
  "What presence will you bring today?",
  "What attention will you give today?",
  "What time will you invest today?",
  "What money will you spend wisely today?",
  "What resource will you use intentionally today?",
  "What skill will you practice today?",
  "What knowledge will you gain today?",
  "What creativity will you express today?",
  "What problem will you solve today?",
  "What innovation will you create today?",
  "What impact will you make today?",
  "What contribution will you give today?",
  "What service will you offer today?",
  "What generosity will you show today?",
  "What leadership will others see today?",
  "What example will you set today?",
  "What influence will you have today?",
  "What change will you start today?",
  "What transformation are you beginning today?",
  "What growth are you committing to today?",
  "What breakthrough are you ready for today?",
  "What victory will you claim today?",
  "What celebration are you earning today?",
  "What pride will you feel tonight?",
  "What freedom are you building today?",
  "What independence are you fighting for today?",
  "What truth will you speak today?",
  "What action will define you today?",
  "What habit will compound today?",
  "What choice will echo tomorrow?",
  "What decision will shape your future today?",
  "What moment will you never forget from today?",
  "What reason will you have to smile tonight?",
  "What evidence of progress will you see today?",
  "What proof of effort will you create today?",
  "What momentum will you build toward your dreams today?",
  "What vision of your future will you step into today?",
  "What version of yourself will you embody today?",
  "What reason to keep going will you find today?",
  "What unstoppable energy will you create today?",
  "What unbreakable focus will you maintain today?",
  "What unwavering commitment will you demonstrate today?",
] as const;

export type ReflectionQuestion = typeof DEFAULT_REFLECTION_QUESTIONS[number];

/**
 * Get a reflection question based on index (rotates through the list)
 * Or get a random question if no index provided
 */
export function getReflectionQuestion(index?: number): ReflectionQuestion {
  // Use random question for variety
  const randomIndex = Math.floor(Math.random() * DEFAULT_REFLECTION_QUESTIONS.length);
  return DEFAULT_REFLECTION_QUESTIONS[randomIndex];
}

/**
 * Total number of available reflection questions
 */
export const REFLECTION_QUESTION_COUNT = DEFAULT_REFLECTION_QUESTIONS.length;
