import {
  MOTIVATIONAL_SENTENCE_COUNT_MAX,
  MOTIVATIONAL_SENTENCE_COUNT_MIN,
} from "./AppConstants";

export const DEFAULT_MOTIVATIONAL_SENTENCES = [
  "I wake up with purpose.",
  "Today I choose progress.",
  "I am full of energy and focus.",
  "I create my own success.",
  "I am disciplined and consistent.",
  "I am growing every day.",
  "I attract positive outcomes.",
  "I am confident in my abilities.",
  "I take action without fear.",
  "I am proud of my journey.",
  "I deserve success and happiness.",
  "I stay calm and focused.",
  "I learn from every experience.",
  "I turn obstacles into opportunities.",
  "I am stronger than my doubts.",
  "I am committed to my goals.",
  "I make things happen.",
  "I am resilient and powerful.",
  "I move forward with confidence.",
  "I believe in my vision.",
  "I choose discipline over excuses.",
  "I am improving every single day.",
  "I am fearless in pursuit of my goals.",
  "I am focused on what matters.",
  "I am building a better future.",
  "I am in charge of my actions.",
  "I am mentally strong.",
  "I am ready for today.",
  "I embrace challenges with courage.",
  "I am becoming my best self.",
  "I stay consistent no matter what.",
  "I am driven and motivated.",
  "I achieve what I set my mind to.",
  "I am calm under pressure.",
  "I turn effort into results.",
  "I trust the process.",
  "I am improving my life daily.",
  "I welcome success into my life.",
  "I act with clarity and purpose.",
  "I am proud of my discipline.",
  "I am building strong habits.",
  "I am focused on growth.",
  "I am patient and persistent.",
  "I rise above negativity.",
  "I am solution-oriented.",
  "I am productive and efficient.",
  "I show up every day.",
  "I take control of my future.",
  "I am capable of greatness.",
  "I push beyond my limits.",
  "I am dedicated to my dreams.",
  "I am mentally unstoppable.",
  "I keep moving forward.",
  "I make progress daily.",
  "I stay committed to my path.",
  "I am confident in my decisions.",
  "I turn ideas into action.",
  "I am always learning.",
  "I am focused on success.",
  "I take responsibility for my life.",
  "I am disciplined in my actions.",
  "I grow stronger every day.",
  "I am becoming more confident.",
  "I stay positive and determined.",
  "I take bold steps forward.",
  "I am aligned with my goals.",
  "I am in control of my mindset.",
  "I build momentum daily.",
  "I trust my journey.",
  "I am proud of my effort.",
  "I choose growth over comfort.",
  "I am unstoppable today.",
  "I make today count.",
  "I am focused on my priorities.",
  "I am building success step by step.",
  "I am stronger than yesterday.",
  "I act with confidence.",
  "I am driven by purpose.",
  "I overcome every obstacle.",
  "I am committed to excellence.",
  "I stay focused on my vision.",
  "I believe in my strength.",
  "I take consistent action.",
  "I am disciplined and focused.",
  "I move closer to my goals today.",
  "I am energized and ready.",
  "I create opportunities.",
  "I am proud of who I am becoming.",
  "I stay motivated and inspired.",
  "I am clear about my goals.",
  "I keep improving daily.",
  "I am determined to succeed.",
  "I take action now.",
  "I am focused and unstoppable.",
  "I stay committed to my growth.",
  "I am building my dream life.",
  "I embrace progress over perfection.",
  "I am capable and confident.",
  "I show up with full energy.",
  "I make myself proud today.",
] as const;

export function getRandomMotivationalSentenceCount(): number {
  const range = MOTIVATIONAL_SENTENCE_COUNT_MAX - MOTIVATIONAL_SENTENCE_COUNT_MIN + 1;
  return MOTIVATIONAL_SENTENCE_COUNT_MIN + Math.floor(Math.random() * range);
}

export function getRandomMotivationalSentences(count?: number): string[] {
  const n = count ?? getRandomMotivationalSentenceCount();
  const shuffled = [...DEFAULT_MOTIVATIONAL_SENTENCES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
