/**
 * Night-time motivational sentences for the Night Guide (Unwind) flow.
 * These replace the morning-oriented sentences when winding down.
 */

export const DEFAULT_NIGHT_MOTIVATIONAL_SENTENCES = [
  "Let go of today and rest.",
  "You did enough today.",
  "Tomorrow is a fresh start.",
  "Release what you cannot change.",
  "Your rest is productive too.",
  "Breathe out the stress.",
  "You are safe to rest now.",
  "The day is done — let it go.",
  "Sleep repairs what the day wore down.",
  "Quiet your mind and find peace.",
  "You showed up today — be proud.",
  "Rest is an act of self-respect.",
  "Tomorrow's energy begins tonight.",
  "Lower your shoulders. Unclench your jaw.",
  "The world can wait until morning.",
  "Every ending is a new beginning.",
  "Honour your effort today.",
  "You have permission to rest.",
  "Clear your mind. Release the day.",
  "Peace begins where worry ends.",
  "Your mind deserves stillness.",
  "Close your eyes and trust tomorrow.",
  "You carried enough today. Put it down.",
  "Healing happens when you rest.",
  "Sleep is the reset button.",
  "The night is your sanctuary.",
  "Gratitude for today. Hope for tomorrow.",
  "Let the silence restore you.",
  "You are enough, exactly as you are.",
  "Rest without guilt.",
  "The moon reminds us to rest.",
  "Not everything needs to be solved today.",
  "Surrender the day to the night.",
  "Your body earned this rest.",
  "Quiet the noise. Find your calm.",
  "Be gentle with yourself tonight.",
  "Tomorrow will meet you rested.",
  "The night holds space for you.",
  "Breathe in peace. Breathe out tension.",
  "You carried the day well.",
  "Rest is not a reward — it is a need.",
  "Allow yourself to soften.",
  "The stars will watch over you.",
  "Drop the weight of the day.",
  "You prepared for tomorrow by surviving today.",
  "Stillness is not emptiness.",
  "Peaceful sleep starts with a peaceful mind.",
  "The night is kind to those who rest.",
  "Let gratitude fill your last thoughts.",
  "You tried your best and that is enough.",
  "Forgive yourself for what went wrong.",
  "Every night resets the story.",
  "Silence is the language of renewal.",
  "Put the day to bed with kindness.",
  "Your worth does not depend on today's output.",
  "Restoration happens in the dark.",
  "Let the day dissolve like a dream.",
  "You are allowed to stop.",
  "The night brings clarity.",
  "Comfort is found in letting go.",
  "Rest deeply. Rise renewed.",
  "The only thing left to do is rest.",
  "Your mind has earned its quiet.",
  "Tonight you recharge. Tomorrow you thrive.",
  "Nothing more is required of you today.",
  "Sleep is wisdom your body already knows.",
  "Trust that tomorrow holds what you need.",
  "The night wraps you in stillness.",
  "Let go and let sleep carry you.",
  "All is well. Rest now.",
  "You don't have to figure it all out tonight.",
  "The mattress is your landing place.",
  "Give yourself the gift of deep rest.",
  "Your only task now is to rest.",
  "Calm your thoughts like still water.",
  "What is meant for you will meet you tomorrow.",
  "Your mind deserves a break from planning.",
  "The night is not for worrying.",
  "Breathe slowly. The day is over.",
  "Rest is how you prepare for greatness.",
  "You are not what you produced today.",
  "Sleep is the bridge to a better tomorrow.",
  "Soften your body. Quiet your mind.",
  "The day gave you enough. Rest.",
  "Courage is also knowing when to stop.",
  "You have nothing left to prove tonight.",
  "Let the moonlight soothe your thoughts.",
  "Restoration begins with surrender.",
  "The night loves those who pause.",
  "Be still and let the world turn without you.",
  "Sleep is the deepest form of trust.",
  "Your best ideas will wait until morning.",
  "The day is complete. You are complete.",
  "Rest with the certainty that you are cared for.",
  "Wrap yourself in the comfort of the night.",
  "Peace is not a destination — it is tonight.",
  "You owe yourself the gift of deep sleep.",
  "Let the last thought be one of peace.",
  "No email, no deadline, no worry matters tonight.",
  "Rest today so you can rise tomorrow.",
  "The dark is not empty — it is full of possibility.",
  "You are safe. You are held. Rest now.",
  "Sleep is the ultimate form of self-care.",
  "Let every exhale release the day.",
  "You have arrived at the end of today — rest.",
  "The world was here before you and will be after. Rest.",
  "Your mind, like a forest, needs night to grow stronger.",
  "Do not carry yesterday into tomorrow. Rest between them.",
  "Every great day begins with a good night.",
] as const;

export function getRandomNightMotivationalSentences(count?: number): string[] {
  const n = count ?? Math.floor(Math.random() * 5) + 5; // 5-9 sentences like morning version
  const shuffled = [...DEFAULT_NIGHT_MOTIVATIONAL_SENTENCES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
