import type { Quote } from "./types";

export const DEFAULT_QUOTES: Omit<Quote, "id">[] = [
  { text: "The early morning has gold in its mouth.", author: "Benjamin Franklin", active: true },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier", active: true },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi", active: true },
  { text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki", active: true },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "George Lorimer", active: true },
  { text: "Every morning brings new potential.", author: "Unknown", active: true },
  { text: "Rise up, start fresh, see the bright opportunity in each day.", author: "Unknown", active: true },

  { text: "When it feels scary to jump, that is exactly when you jump. Otherwise you end up staying in the same place your whole life.", author: "Abel Morales", active: true },
  { text: "The faster you do the hard things you want to avoid, the faster you'll get the good things you actually want.", author: "Unknown", active: true },
  { text: "Worrying doesn't take away tomorrow's trouble; it takes away today's peace.", author: "Unknown", active: true },
  { text: "If you don’t control your mind, someone else will.", author: "Unknown", active: true },
  { text: "You can’t have courage without being scared.", author: "Unknown", active: true },
  { text: "Struggle is nature’s way of strengthening you.", author: "Unknown", active: true },
  { text: "Trying is planning to fail. Commit to doing—and you will.", author: "Unknown", active: true },
  { text: "Discuss or decide — never both. Discussion ends when decision starts.", author: "Unknown", active: true },
  { text: "The price of progress is pain.", author: "Unknown", active: true },
  { text: "Progress compounds, just like money.", author: "Unknown", active: true },
  { text: "If you don’t swing, you can’t hit the home run.", author: "Unknown", active: true },
  { text: "Habit missed once is a mistake; missed twice is a new habit forming.", author: "Unknown", active: true },
  { text: "Nothing destroys you faster than your own mind.", author: "Unknown", active: true },
  { text: "Everyone is a slave to something — choose wisely.", author: "Unknown", active: true },
  { text: "A moment of pain can buy a lifetime of glory.", author: "Unknown", active: true },
  { text: "Achievement demands disruption — comfort never creates greatness.", author: "Unknown", active: true },
  { text: "Spend your time and energy chasing something greater.", author: "Unknown", active: true },
  { text: "Nothing ever works well the first time. Refine, repeat, rise.", author: "Unknown", active: true },
  { text: "Go all the way, or don’t even start.", author: "Unknown", active: true },
  { text: "Where you point your attention is where your life goes.", author: "Unknown", active: true },
  { text: "If you speak well, you can sell hell as heaven.", author: "Unknown", active: true },

  { text: "Each sunrise is a signal to start again stronger.", author: "Unknown", active: true },
  { text: "Discipline is choosing what you want most, over what you want now.", author: "Unknown", active: true },
  { text: "Don’t wait for the mood to move — move and the mood will follow.", author: "Unknown", active: true },
  { text: "You don’t find motivation; you create it through action.", author: "Unknown", active: true },
  { text: "Be proud of small wins — they build unstoppable momentum.", author: "Unknown", active: true },
  { text: "The way you start your morning defines how you end your day.", author: "Unknown", active: true },
  { text: "Effort beats talent when talent stops trying.", author: "Unknown", active: true },
  { text: "You are one disciplined morning away from changing everything.", author: "Unknown", active: true },
  { text: "Don’t just chase success — build the habits that attract it.", author: "Unknown", active: true },
  { text: "Fear loses its power the second you face it.", author: "Unknown", active: true },
  { text: "Growth begins when comfort ends.", author: "Unknown", active: true },
  { text: "Keep moving — momentum solves more problems than motivation.", author: "Unknown", active: true },
  { text: "The way you do one thing is the way you do everything.", author: "Unknown", active: true },
  { text: "Show up even when you don’t feel ready.", author: "Unknown", active: true },
  { text: "Action cures doubt.", author: "Unknown", active: true },
  { text: "Hard choices create easy lives; easy choices create hard ones.", author: "Unknown", active: true },
  { text: "You can’t improve what you don’t start.", author: "Unknown", active: true },
  { text: "Persistence breaks resistance.", author: "Unknown", active: true },
  { text: "Every great day starts with one decisive move.", author: "Unknown", active: true },
  { text: "Don’t let your comfort zone become your prison.", author: "Unknown", active: true },
  { text: "Energy follows intention — aim deliberately.", author: "Unknown", active: true },
  { text: "Even failure teaches momentum. Keep moving.", author: "Unknown", active: true },
  { text: "Victory starts in the mind before it shows in the world.", author: "Unknown", active: true },
  { text: "The best mornings begin with strong purpose and quiet confidence.", author: "Unknown", active: true },
  { text: "You can’t be unstoppable if you keep stopping.", author: "Unknown", active: true },
  { text: "Decide once, act daily.", author: "Unknown", active: true },
  { text: "You become powerful when you outgrow excuses.", author: "Unknown", active: true },
  { text: "A disciplined morning turns chaos into clarity.", author: "Unknown", active: true },

  { text: "Either you run the day or the day runs you.", author: "Jim Rohn", active: true },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", active: true },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston", active: true },
  { text: "Dreams don’t work unless you do.", author: "John C. Maxwell", active: true },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu", active: true },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", active: true },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", active: true },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", active: true },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", active: true },
  { text: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou", active: true },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", active: true },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", active: true },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson", active: true },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", active: true },
  { text: "The harder the conflict, the greater the triumph.", author: "George Washington", active: true },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", active: true },
  { text: "Well begun is half done.", author: "Aristotle", active: true },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh", active: true },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien", active: true },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", active: true },
];