export const DEFAULT_NIGHT_REFLECTION_QUESTIONS = [
  "What was the best part of your day?",
  "What did you learn today?",
  "What are you grateful for today?",
  "Did you accomplish your main goal today?",
  "What could you have done better today?",
  "How are you feeling right now?",
  "What was one challenge you faced today?",
  "What made you smile today?",
  "What are you looking forward to tomorrow?",
  "Did you help someone today?",
  "What drained your energy today?",
  "What energized you today?",
  "Are you proud of how you spent your day?",
  "What would you do differently if you could relive today?",
  "What is one thing you want to remember from today?",
  "How did you take care of yourself today?",
  "What positive impact did you have today?",
  "What distracted you today and how can you avoid it tomorrow?",
  "What conversation stood out to you today?",
  "What does tomorrow need to look like for you to feel fulfilled?",
  "What small win did you have today?",
  "What did you do today that moved you closer to your goals?",
  "What thought kept coming back to you today?",
  "What are you most proud of handling well today?",
  "What habit did you practice today?",
  "What habit do you want to improve tomorrow?",
  "What did today teach you about yourself?",
  "What was your mood most of the day?",
  "What moment felt peaceful today?",
  "What stressed you out the most today?",
  "What did you avoid today that needs attention tomorrow?",
  "What is one unfinished task you want to complete tomorrow?",
  "What inspired you today?",
  "What temptation did you resist today?",
  "What choice today reflected your values?",
  "What choice today did not reflect your values?",
  "What are three good things that happened today?",
  "What do you need to let go of before sleeping?",
  "What would make tomorrow easier for you?",
  "What made today meaningful?",
  "Who supported you today?",
  "How did you support yourself today?",
  "What kind thing did you do today?",
  "What kind thing did someone do for you today?",
  "What part of today felt difficult but necessary?",
  "What did you spend too much time on today?",
  "What deserved more of your time today?",
  "What did you say no to today?",
  "What should you say no to tomorrow?",
  "What made you feel confident today?",
  "What made you doubt yourself today?",
  "How did you respond to pressure today?",
  "Did you stay true to your priorities today?",
  "What pulled you away from your priorities today?",
  "What is one thing you handled better than before?",
  "What is one thing you still need to work on?",
  "What emotion do you need to process tonight?",
  "What bothered you today that may not matter next week?",
  "What mattered most today?",
  "What did you do today that your future self will thank you for?",
  "What excuse did you make today?",
  "What truth do you need to accept tonight?",
  "What did you do even when you did not feel like it?",
  "What does progress look like from today’s effort?",
  "What lesson from today can help you tomorrow?",
  "What did today reveal about your current priorities?",
  "What part of your routine helped you most today?",
  "What part of your routine needs adjustment?",
  "What did you consume today that affected your mindset?",
  "What did you create today?",
  "What problem did you solve today?",
  "What did you postpone today and why?",
  "What fear influenced your actions today?",
  "What courage did you show today?",
  "What boundary did you maintain today?",
  "What boundary do you need to set tomorrow?",
  "What did you do for your physical health today?",
  "What did you do for your mental health today?",
  "How present were you today?",
  "When did you feel most focused today?",
  "When did you feel most distracted today?",
  "What can you forgive yourself for today?",
  "What can you appreciate yourself for today?",
  "What did you prove to yourself today?",
  "What is something simple that brought you joy today?",
  "What made you feel alive today?",
  "What did you notice about your thoughts today?",
  "What story were you telling yourself today?",
  "Was that story helpful or limiting?",
  "What would a better mindset for tomorrow sound like?",
  "What would make you wake up with purpose tomorrow?",
  "What is one promise you want to keep to yourself tomorrow?",
  "What is one brave thing you can do tomorrow?",
  "What is one important thing you should stop delaying?",
  "What did today cost you emotionally?",
  "What did today give you emotionally?",
  "What would make tomorrow a win?",
  "What would make tomorrow calmer?",
  "What would make tomorrow more productive?",
  "What would make tomorrow more joyful?",
  "What reminder do you need before you sleep?",
  "What is one reason to feel hopeful tonight?",
  "Why should you be proud of yourself today?",
  "What is motivating you to keep going right now?",
  "What dream are you working toward, even slowly?",
  "What version of yourself are you becoming?",
  "What is one more reason not to give up?",
  "What can tomorrow be a fresh start for?",
] as const;

export function getRandomNightReflectionQuestion(): string {
  const idx = Math.floor(Math.random() * DEFAULT_NIGHT_REFLECTION_QUESTIONS.length);
  return DEFAULT_NIGHT_REFLECTION_QUESTIONS[idx];
}
