import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  todaySection: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  todayLeft: { flex: 1 },
  todayLabel: {
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  todayTime: { fontSize: 18, fontWeight: "700" },
  todayStatusBadge: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20 },
  todayStatusText: { fontSize: 14, fontWeight: "600" },
  todayEmpty: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  todayEmptyText: { fontSize: 14, fontWeight: "500" },
  list: { padding: 16, paddingBottom: 100 },
  card: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  cardBody: { flex: 1 },
  cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  time: { fontSize: 28, fontWeight: "700" },
  label: { fontSize: 14, marginTop: 2 },
  weekdaysRow: { flexDirection: "row", gap: 8, marginTop: 8 },
  weekday: { fontSize: 12, width: 28, textAlign: "center" },
  toggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  toggleKnob: { width: 20, height: 20, borderRadius: 10 },
  deleteBtn: { padding: 8, marginLeft: 8 },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  emptyContainer: { alignItems: "center", paddingTop: 80, gap: 12 },
  emptyTitle: { fontSize: 20, fontWeight: "700" },
  emptySubtitle: { fontSize: 14, textAlign: "center", paddingHorizontal: 40 },
});
